config/routes.rb
Rails.application.routes.draw do
  # Root
  authenticated :user do
    root to: redirect('home'), as: :root_home
    get :home, to: 'home#index', as: :home
  end
  root to: 'welcome#index', as: :welcome

  # Devise routes
  devise_for :users,
             controllers:
             {
               omniauth_callbacks: 'users/omniauth_callbacks',
               registrations: 'users/registrations'

             }

  # Concerns
  concern :commentable do
    resources :comments, only: %i[index create destroy], concerns: :likeable
  end

  concern :likeable do
    resources :likes, only: %i[index create destroy]
  end

  # Users and nested resources
  resources :users, only: %i[show] do
    resources :status_updates, shallow: true, concerns: %i[commentable likeable]
    resource :profile, only: %i[edit update]
    post :set_avatar, to: 'profiles#set_avatar'
    post :set_cover, to: 'profiles#set_cover'
    resources :friendships, only: %i[index create update destroy]
    resources :photo_albums do
      resources :images, except: :new,
                         shallow: true,
                         concerns: %i[commentable likeable]
    end
  end

  # Notifications
  resources :notifications, only: :index do
    post 'mark_as_read', on: :collection
    post 'clear', on: :collection
  end

  # Autocomplete & Search
  get :autocomplete, to: 'autocomplete#index'

  namespace :autocomplete do
    get :friends
  end

  namespace :search do
    get :users, :status_updates, :images, :comments
  end

  # Email check
  get :check_email, to: 'users#check_email'

  # Conversations and messages
  resources :conversations, except: %i[edit create update] do
    get :unread_count, on: :collection
  end
  resources :messages, only: %i[create]
end

app/views/shared/_errors.html.haml
- if object.errors.any?
  .ui.error.message#error_explanation{ 'style': 'display: block;'}
    The form contains #{pluralize(object.errors.count, "error")}.
    %ul.list
      - object.errors.full_messages.each do |msg|
        %li= msg

app/views/shared/_feedback_actions.html.haml
- comments_path = send("#{feedbackable.class.to_s.underscore.downcase}_comments_path", feedbackable)
- likes_path = send("#{feedbackable.class.to_s.underscore.downcase}_likes_path", feedbackable)
- can_feedback = policy(feedbackable).feedback?
.content.statistics
  // Like action and statistics
  %span

    - if can_feedback
      = render_likes feedbackable

    %span.likes_count{ 'data-link': likes_path,
      'data-behavior': 'like-count-container',
      'data-inverted': '' }
      = pluralize feedbackable.likes.count, 'like'

  // Comment action and statistics
  %span.whitespace--left

    - if can_feedback
      %a{ 'data-tooltip': 'Comment', 'data-inverted': '' }
        %i.comment.icon{ 'data-behavior': 'comment-link' }

  %a.comments_count{ 'data-behavior': 'show-comments',
    'data-link': comments_path, 'data-tooltip': 'See comments', 'data-inverted': '' }
    = pluralize feedbackable.comments.count, 'comment'

- if can_feedback
  // Comment form
  .content.comment__form{ 'data-behavior': 'comment-form' }
    = form_with model: [feedbackable, Comment.new],
      class: 'ui form' do |form|

      = hidden_field_tag 'comment[author_id]', current_user.id

      .field
        = form.text_area :text, placeholder: 'Add comment', rows: 2

      .actions
        = form.submit 'Comment',
          class: 'ui blue right floated comment-submit button'

      = link_to 'Cancel', nil,
        data: { 'behavior': 'cancel-link' },
        class: 'ui right floated basic blue button'

app/views/shared/_flash.html.haml
- if flash.present?
  - flash.each do |type, message|
    %div{ class: "ui row message #{flash_class(type)}"}
      .header= message

app/views/shared/_flash_js.js.erb
var flashTimeout;
clearTimeout(flashTimeout);
$('#flash').html('<%= j render partial: "shared/flash" %>').show();
flashTimeout = setTimeout( function() {
  $('#flash').slideUp(250);
}, 4000);

<% flash.clear %>