config/routes.rb
Rails.application.routes.draw do
  # Root
  authenticated :user do
    root to: redirect('home'), as: :root_home
    get :home, to: 'home#index', as: :home
  end
  root to: 'welcome#index', as: :welcome

  # Devise routes
  devise_for :users,
             controllers:
             {
               omniauth_callbacks: 'users/omniauth_callbacks',
               registrations: 'users/registrations'

             }

  # Concerns
  concern :commentable do
    resources :comments, only: %i[index create destroy], concerns: :likeable
  end

  concern :likeable do
    resources :likes, only: %i[index create destroy]
  end

  # Users and nested resources
  resources :users, only: %i[show] do
    resources :status_updates, shallow: true, concerns: %i[commentable likeable]
    resource :profile, only: %i[edit update]
    post :set_avatar, to: 'profiles#set_avatar'
    post :set_cover, to: 'profiles#set_cover'
    resources :friendships, only: %i[index create update destroy]
    resources :photo_albums do
      resources :images, except: :new,
                         shallow: true,
                         concerns: %i[commentable likeable]
    end
  end

  # Notifications
  resources :notifications, only: :index do
    post 'mark_as_read', on: :collection
    post 'clear', on: :collection
  end

  # Autocomplete & Search
  get :autocomplete, to: 'autocomplete#index'

  namespace :autocomplete do
    get :friends
  end

  namespace :search do
    get :users, :status_updates, :images, :comments
  end

  # Email check
  get :check_email, to: 'users#check_email'

  # Conversations and messages
  resources :conversations, except: %i[edit create update] do
    get :unread_count, on: :collection
  end
  resources :messages, only: %i[create]
end

app/views/shared/navbar/_conversations.html.haml
= link_to conversations_path,
  class: 'ui item',
  id: 'navbar_message_count' do
  .right.pointing.ui.label{ 'data-behavior': 'unread-msg-count' } 0
  %i.comments.icon

app/views/shared/navbar/_footer.html.haml
.ui.transparent.inverted.vertical.footer.segment
  %p.item
    Made with
    = image_tag 'brain-icon.png', class: 'ui mini brain spaced image'
    by
    %a{ href: 'https://github.com/chanjman', target: '_blank' }
      Mario Zugaj

app/views/shared/navbar/_guest_navbar.html.haml
.ui.secondary.menu
  .item
    = link_to welcome_path do
      %h1.ui.inverted.header PeopleBook
  .right.menu
    .item
      = link_to 'Log in', new_user_session_path, class: 'ui blue button'

app/views/shared/navbar/_navbar.html.haml
- if current_user
  = render 'shared/navbar/user_navbar'
- else
  = render 'shared/navbar/guest_navbar'

app/views/shared/navbar/_notifications.html.haml
.ui.floating.top.right.pointing.scrolling.dropdown.item#notifications{ 'data-behavior': 'notifications',
  'data-link': 'notifications-link' }

  /* Notifications bell icon and label
  .ui.right.pointing.label{ 'data-behavior': 'unread-count' } 0
  %i.bell.icon

  /* Notifications dropdown
  .menu
    // Notification items
    .items{ 'data-behavior': 'notification-items' }

app/views/shared/navbar/_request_notifications.html.haml
.ui.floating.pointing.top.right.dropdown.item#requests

  // Notifications bell icon and label
  %div{ class: class_string('right pointing ui label',
    'red' => @requested_friends.exists?) }= @requested_friends.size
  %i.users.icon

  // Notifications dropdown
  .menu
    - if @requested_friends.any?
      - @requested_friends.each do |requested_friend|
        .item
          .request.content
            .description
              .ui.avatar.image
                = image_tag requested_friend.avatar.url :thumb
              %span.ui.small.header
                = link_to requested_friend.name, user_path(requested_friend)
              %span.text requested to be your friend
            %span.request.buttons
              // Approve button
              = link_to 'Approve',
                user_friendship_path(current_user, find_friendship(requested_friend)),
                method: 'patch',
                class: 'ui mini positive request button'
              // Decline button
              = link_to 'Decline',
                user_friendship_path(current_user, find_friendship(requested_friend)),
                method: 'delete',
                class: 'ui mini negative request button'
    - else
      .item
        %span No new friend requests. Make some new friends?

app/views/shared/navbar/_search.html.haml
= form_with url: search_users_path,
  class: 'ui category search item',
  method: :get,
  local: true do

  .ui.link.icon.input
    %input.prompt{ name: 'q', placeholder: 'Search people, updates...'}
      %i.ui.search.icon
  .results

app/views/shared/navbar/_user_links.html.haml
.ui.floating.pointing.top.right.hover.dropdown.item#user_links
  = link_to user_path(current_user) do
    = image_tag current_user.profile.avatar.url(:thumb), class: 'ui avatar image'
    = current_user.name

  .menu
    = link_to user_friendships_path(current_user), class: 'item' do
      %i.users.icon
      Friends
    = link_to edit_user_registration_path(current_user), class: 'item' do
      %i.settings.icon
      Edit Account
    = link_to edit_user_profile_path(current_user), class: 'item' do
      %i.configure.icon
      Edit profile
    .divider
    = link_to destroy_user_session_path, class: 'item', method: 'delete' do
      %i.sign.out.icon
      Log out

app/views/shared/navbar/_user_navbar.html.haml
.ui.inverted.borderless.blue.top.fixed.menu

  //Logo
  .item
    = link_to 'PeopleBook', home_path, class: 'ui inverted header'

  // Search
  = render 'shared/navbar/search'

  // Right navbar menu
  .right.menu

    // Friend requests notifications
    = render 'shared/navbar/request_notifications'

    // Notifications
    = render 'shared/navbar/notifications'

    // Messages
    = render 'shared/navbar/conversations'

    // Current user profile links
    = render 'shared/navbar/user_links'